ARG default_py_version=3.8

FROM --platform=$BUILDPLATFORM ubuntu:22.04

ARG BUILDPLATFORM
ARG default_py_version

ENV PY_VERSION="${default_py_version}"

RUN if ! [ "$BUILDPLATFORM" = "linux/arm64" ] ; then exit 1; fi

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq update && \
  apt-get -y install software-properties-common && \
  add-apt-repository -y ppa:deadsnakes/ppa && \
  apt-get -qq update && \
  apt-get install --no-install-recommends -yq \
    art-nextgen-simulation-tools \
    bc \
    bcftools \
    bedtools \
    build-essential \
    bwa \
    cmake \
    curl \
    gawk \
    git \
    jellyfish \
    python3-dna-jellyfish \
    libbz2-dev \
    libhdf5-dev \
    liblzma-dev \
    protobuf-compiler \
    python${PY_VERSION} \
    python${PY_VERSION}-dev \
    python${PY_VERSION}-distutils \
    python3-pip \
    python3-pkgconfig \
    sambamba=0.8.2+dfsg-2 \
    samtools \
    tabix \
    unzip \
    zlib1g-dev \
    && \
  apt-get clean -y && \
  rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1

RUN mkdir -p /opt/samblaster && \
  curl -SL https://github.com/GregoryFaust/samblaster/releases/download/v.0.1.26/samblaster-v.0.1.26.tar.gz \
  | tar -xzC /opt/samblaster --strip-components=1 && \
  make -C /opt/samblaster && \
  cp /opt/samblaster/samblaster /usr/local/bin/.

RUN curl -SL https://github.com/brentp/goleft/releases/download/v0.2.6/goleft_linux_aarch64 \
  -o /usr/local/bin/goleft \
  && chmod +x /usr/local/bin/goleft

ADD . /opt/npsv2

# Install dependencies
# We now seem to need to pin h5py...
RUN python3 -m pip install --no-cache-dir setuptools==57.5.0 h5py==3.10.0
RUN python3 -m pip install --no-cache-dir -r /opt/npsv2/requirements.txt

# Install npsv2
WORKDIR /opt/npsv2
RUN python3 setup.py install