import argparse, io, os, sys, tempfile, unittest
from unittest.mock import patch
import pysam
from npsv2.multiallelic import merge_into_multiallelic

FILE_DIR = os.path.join(os.path.dirname(__file__), "data")

@unittest.skipUnless(os.path.exists("/data/human_g1k_v37.fasta"), "Reference genome not available")
class CreateMultiAllelicVariantTestSuite(unittest.TestCase):
    def setUp(self):
        self.tempdir = tempfile.TemporaryDirectory()
        self.vcf_path = os.path.join(self.tempdir.name, "test.vcf")
        with open(self.vcf_path, "w") as vcf_file:
            vcf_file.write(
                """##fileformat=VCFv4.2
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this record">
##INFO=<ID=SVLEN,Number=.,Type=Integer,Description="Difference in length between REF and ALT alleles">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##ALT=<ID=DEL,Description="Deletion">
##contig=<ID=8,length=146364022>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
8	117691102	pbsv.DEL.24695	GGGGGGGGTCAGCCCCCCGCCCGGCCAGCCGCCCCGTCCGGGAGGTGAGGGGCTCCTCTGCCCGGCCGCCCCTACTGGGAAGTGAGGAGCCCCTCTGCCCGGCCAGTCGCCCCGTCCAGGAGGGAGGTGGGGGGGTCAGCCCCCCGCCCGGCCAGCCGCCCAGTCCGGGAGGTGAGGGGCGCCTCTGCCCGGCCGCCCCTACTGGGAAGTGAGGAGTCCCTCTGCCCGGCCAGCCTCCCCGTCCGGGAGGGGGGAGGGGGGGTCAGCCCCCTGCCCGGCCAGCCGCCCCGTCCGGGAGGGAGGTGGTGGGGGTCAGCCCCCCGCCCGGCCAGCCGCCCCGTCCGGGAGGTGAGGGGCGCCTCTGCCCGGCCGCCCCTACTGGGAAGTGAGGAGCCCCTCTGCCCGGCCAGCCGCCCCGTCCGGGAGGGAGGTGGGGGGGTCAGCCCCCCGCCCGGCCAGCCGCCCCATCCGGGAGGAAGGTGGGGGGGTCAGCCCCCCGCCCGGTCAGCCCCCCGCCCGGCCAGCCGCCCCGTCCGGGAGGGAGGTGGGGGGATCAGCCCCCCGCCTGGCCAGCCGCCCCGTCCGGGAGGTGAGGGGCGCCTCTGCCCGGCCGCCCCTACTGGGAAGTGAGGAGCCCCTCTGCCCGGCCAGCCGCCCCGTCCGGGAGGGAGGTGGGGGGGTCAGCCCCCCGCCCGGCCAGCCGCCCCATCCGGGAGGAAGGT	G	.	PASS	SVTYPE=DEL;END=117691823;SVLEN=-721	GT	0/1
8	117691336	pbsv.DEL.24696	CTCCCCGTCCGGGAGGGGGGAGGGGGGGTCAGCCCCCTGCCCGGCCAGCC	C	.	PASS	SVTYPE=DEL;END=117691385;SVLEN=-49	GT	0/1
"""
            )

    def tearDown(self):
        self.tempdir.cleanup()

    # Expected result
    #8	117691102	.	GGGGGGGGTCAGCCCCCCGCCCGGCCAGCCGCCCCGTCCGGGAGGTGAGGGGCTCCTCTGCCCGGCCGCCCCTACTGGGAAGTGAGGAGCCCCTCTGCCCGGCCAGTCGCCCCGTCCAGGAGGGAGGTGGGGGGGTCAGCCCCCCGCCCGGCCAGCCGCCCAGTCCGGGAGGTGAGGGGCGCCTCTGCCCGGCCGCCCCTACTGGGAAGTGAGGAGTCCCTCTGCCCGGCCAGCCTCCCCGTCCGGGAGGGGGGAGGGGGGGTCAGCCCCCTGCCCGGCCAGCCGCCCCGTCCGGGAGGGAGGTGGTGGGGGTCAGCCCCCCGCCCGGCCAGCCGCCCCGTCCGGGAGGTGAGGGGCGCCTCTGCCCGGCCGCCCCTACTGGGAAGTGAGGAGCCCCTCTGCCCGGCCAGCCGCCCCGTCCGGGAGGGAGGTGGGGGGGTCAGCCCCCCGCCCGGCCAGCCGCCCCATCCGGGAGGAAGGTGGGGGGGTCAGCCCCCCGCCCGGTCAGCCCCCCGCCCGGCCAGCCGCCCCGTCCGGGAGGGAGGTGGGGGGATCAGCCCCCCGCCTGGCCAGCCGCCCCGTCCGGGAGGTGAGGGGCGCCTCTGCCCGGCCGCCCCTACTGGGAAGTGAGGAGCCCCTCTGCCCGGCCAGCCGCCCCGTCCGGGAGGGAGGTGGGGGGGTCAGCCCCCCGCCCGGCCAGCCGCCCCATCCGGGAGGAAGGT	G,GGGGGGGGTCAGCCCCCCGCCCGGCCAGCCGCCCCGTCCGGGAGGTGAGGGGCTCCTCTGCCCGGCCGCCCCTACTGGGAAGTGAGGAGCCCCTCTGCCCGGCCAGTCGCCCCGTCCAGGAGGGAGGTGGGGGGGTCAGCCCCCCGCCCGGCCAGCCGCCCAGTCCGGGAGGTGAGGGGCGCCTCTGCCCGGCCGCCCCTACTGGGAAGTGAGGAGTCCCTCTGCCCGGCCAGCCCCGCCCCGTCCGGGAGGGAGGTGGTGGGGGTCAGCCCCCCGCCCGGCCAGCCGCCCCGTCCGGGAGGTGAGGGGCGCCTCTGCCCGGCCGCCCCTACTGGGAAGTGAGGAGCCCCTCTGCCCGGCCAGCCGCCCCGTCCGGGAGGGAGGTGGGGGGGTCAGCCCCCCGCCCGGCCAGCCGCCCCATCCGGGAGGAAGGTGGGGGGGTCAGCCCCCCGCCCGGTCAGCCCCCCGCCCGGCCAGCCGCCCCGTCCGGGAGGGAGGTGGGGGGATCAGCCCCCCGCCTGGCCAGCCGCCCCGTCCGGGAGGTGAGGGGCGCCTCTGCCCGGCCGCCCCTACTGGGAAGTGAGGAGCCCCTCTGCCCGGCCAGCCGCCCCGTCCGGGAGGGAGGTGGGGGGGTCAGCCCCCCGCCCGGCCAGCCGCCCCATCCGGGAGGAAGGT   .       PASS    SVTYPE=DEL;END=117691823;SVLEN=-721,-49 GT      1/2
    def test_compound_het_merge(self):
        merge_into_multiallelic(self.vcf_path, "/dev/stdout", "/data/human_g1k_v37.fasta")

    