defaults:
  - pileup
  - simulation: augmented
  - generator: single_depth
  - model: joint_embeddings
  - training
  - optional model_training: ${model}
  - refine
  - command: genotype
  - _self_

threads: 1

reference: ???
shared_reference: null
load_reference: false
stats_path: ???

input: ???
reads: ???
output: ???

sample: null