defaults:
  - pileup: five_channel
  - generator: single
  - simulation: augmented
  - model: joint_embeddings
  - training
  - pileup_generator: ${defaults.1.generator}
    optional: true
  - model_training: ${defaults.3.model}
    optional: true
  - command: genotype

threads: 1

reference: ???
shared_reference: null
stats_path: ???

input: ???
reads: ???
output: ???

sample: null