defaults:
  - pileup
  - generator: single_depth
  - simulation: augmented
  - model: joint_embeddings
  - training
  - model_training: ${defaults.3.model}
    optional: true
  - command: genotype

threads: 1

reference: ???
shared_reference: null
stats_path: ???

input: ???
reads: ???
output: ???

sample: null