defaults:
  - pileup: five_channel
  - generator: single
  - pileup_generator: ${defaults.1.generator}
    optional: true
  - simulation: augmented
  - model: joint_embeddings
  - training

command: genotype
threads: 1

reference: ???
shared_reference: null
stats_path: ???

input: ???
reads: ???
output: ???

sample: null